easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Article
        - App\Entity\Author
        - App\Entity\Category
        - App\Entity\Commentary
        - App\Entity\User
