version: "3.3"
services:
  symfony_rest_blog_api_mysql:
    container_name: symfony_rest_blog_api_mysql
    hostname: by_msql
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root